server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-waste_manager
            uri: http://localhost:8082
            predicates:
              - Path=/waste_manager2/**