server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: ms-waste_manager
            uri: lb://ms-waste_manager
            predicates:
              - Path=/waste_manager/**