server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arc251000/Technical-Test.git
          search-paths: configs
          username: ${GIT-USER}
          password: ${GIT-PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t
